import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../scss/main.scss";
import PageRender from "./PageRender";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PRANTO SHIKDER",
  description: "Generated by create next app",
  keywords:
    "web development, web design, javascript, react, node, angular, vue, html, css, sass, webpack, git, github, npm, yarn, code, programming, tutorial, course",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto} portfolio scrollbar`}
        suppressHydrationWarning={true}
      >
        <PageRender>{children}</PageRender>
      </body>
    </html>
  );
}
